function [b] = EqHPF(Fstop, Fpass)
%EQHPF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
% Generated on: 08-Mar-2023 00:54:29

% Equiripple Highpass filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N     = 15;     % Order
Wstop = 0.5;    % Stopband Weight
Wpass = 0.2;      % Passband Weight
dens  = 20;     % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop Fpass 1], [0 0 1 1], [Wstop Wpass], {dens});

% [EOF]
end