function b = LSHPF(Fstop,Fpass)
%HPFDESIGNER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
% Generated on: 08-Mar-2023 00:49:47

% FIR least-squares Highpass filter designed using the FIRLS function.

% All frequency values are normalized to 1.

N     = 10;     % Order
Wstop = 0.5;    % Stopband Weight
Wpass = 1;      % Passband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop Fpass 1], [0 0 1 1], [Wstop Wpass]);

% [EOF]
end